---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shenziqiao.
--- DateTime: 2/20/23 6:09 PM
---

-- parameter list
-- voucher id
local voucherId = ARGV[1]
-- user id
local userId = ARGV[2]
-- order id
local orderId = ARGV[3]

-- data key
-- stock key
local stockKey = 'seckill:stock:' .. voucherId
-- order key
local orderKey = 'seckill:order:' .. voucherId

-- script business
-- determine if stock is enough
if(tonumber(redis.call('get', stockKey)) <= 0) then
    -- when stock is not enough, return 1
    return 1
end
-- determine if the user placed an order (SISMEMBER orderKey userId
if(redis.call('sismember', orderKey, userId) == 1) then
    -- if exists, duplicate order, return 2
    return 2
end
-- deduct stock (incrby stockKey -1)
redis.call('incrby',stockKey, -1)
-- place order (save user) (sadd orderKey userId)
redis.call('sadd', orderKey, userId)
-- send message to queue xadd stream.orders * k1 v1 k2 v2
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0