---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shenziqiao.
--- DateTime: 2/19/23 12:21 AM
---

-- get thread identifier from lock
local id = redis.call('get', KEYS[1])
-- compare thread identifier and lock identifier
if(id == ARGV[1]) then
    -- unlock
    redis.call('del', KEYS[1])
end
return 0